name: gcd_test
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntsulatest
    run: test-gcd.sh
        
name: same_test
 on: [push]
 jobs:
 io_test:
   name: Use Linux commands
   runs-on: ubuntu-latest
   steps:
   -name: Checkout
   uses: actions/checkout@v4
   -name: Permission Setting
   run: chmod +x gcd.sh test_gcd.sh
   -name: Test Run
   run: ./test-gcd.sh 
